version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "TeamCreated:3:1,TeamUpdated:3:1,TeamDeleted:3:1,PlayerCreated:3:1,PlayerTeamChanged:3:1,PlayerDeleted:3:1,FeeAndPlayerTransferred:3:1,ExchangeRateUpdated:3:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  postgresdb:
    image: postgres:12.4
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    environment:
      - POSTGRES_PASSWORD=casino
  eureka:
    build: ../eureka
    ports: 
     - "8761:8761"
  gateway:
    build: ../gateway
    ports: 
      - "8762:8762"
    environment:
      GATEWAY_EUREKA_CONNECT: eureka:8761
    depends_on:
      - eureka
  team:
    build: ../team
    ports: 
      - "8010:8010"
    environment:
      TEAM_DB_CONNECT: postgresdb:5432
      TEAM_KAFKA_CONNECT: kafka:9092
      TEAM_EUREKA_CONNECT: eureka:8761      
    depends_on:
      - postgresdb
      - kafka
      - eureka
  player:
    build: ../player
    ports: 
      - "8020:8020"
    environment:
      PLAYER_DB_CONNECT: postgresdb:5432
      PLAYER_KAFKA_CONNECT: kafka:9092
      PLAYER_EUREKA_CONNECT: eureka:8761      
    depends_on:
      - postgresdb
      - kafka
      - eureka
  transfer:
    build: ../transfer
    ports: 
      - "8030:8030"
    environment:
      TRANSFER_DB_CONNECT: postgresdb:5432
      TRANSFER_KAFKA_CONNECT: kafka:9092
      TRANSFER_EUREKA_CONNECT: eureka:8761      
    depends_on:
      - postgresdb
      - kafka
      - eureka      
  exchangerate:
    build: ../exchangerate
    environment:
      EXCHANGERATE_KAFKA_CONNECT: kafka:9092
    depends_on:
      - kafka

